#pragma once

// Overrides for CHIP Device Config
#define CHIP_DEVICE_CONFIG_DEVICE_VENDOR_NAME "busware.de"
#define CHIP_DEVICE_CONFIG_DEVICE_VENDOR_ID 0xFFF1
#define CHIP_DEVICE_CONFIG_DEVICE_PRODUCT_NAME "MAX! Bridge"

// Static Matter Setup Code for matter4max
// Setup PIN: 86801101
// Discriminator: 2152
#define CHIP_DEVICE_CONFIG_USE_TEST_SETUP_PIN_CODE 86801101
#define CHIP_DEVICE_CONFIG_USE_TEST_SETUP_DISCRIMINATOR 2152
#define CHIP_DEVICE_CONFIG_USE_TEST_SPAKE2P_ITERATION_COUNT 1000
#define CHIP_DEVICE_CONFIG_USE_TEST_SPAKE2P_SALT "XMMfywrN830Ud/oTcrg/7g=="
#define CHIP_DEVICE_CONFIG_USE_TEST_SPAKE2P_VERIFIER "GrC+7QnAT/Us/VIupAPOLSo0DbsmE4X3uPI6/btuW4cE1fx5v+TnhtQphcA/jZ0GlICqgH0MlbCFGol0TRQQspovcpIW1XVYvHlDwDgUxTWTvxLaueXI6R48rR3Mte/57A=="
